### ISSUE TITLE
Was working, now get value error

### ISSUE THREAD

**Issue by matkam** [kpcyrd/yrd#14]
yrd was just working fine, and after a cjdns reboot (I think), now outputs the following error:

```
$ yrd n
Traceback (most recent call last):
  File "/bin/yrd", line 11, in <module>
    load_entry_point('yrd==0.5.0', 'console_scripts', 'yrd')()
  File "/usr/lib/python3.6/site-packages/yrd/__init__.py", line 14, in main
    dispatch(parser)
  File "/usr/lib/python3.6/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/usr/lib/python3.6/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/usr/lib/python3.6/site-packages/argh/dispatching.py", line 265, in _call
    for line in result:
  File "/usr/lib/python3.6/site-packages/yrd/core.py", line 124, in neighbours
    for peer in c.peerStats():
  File "/usr/lib/python3.6/site-packages/yrd/xcjdns.py", line 145, in peerStats
    yield Peer(**peer)
  File "/usr/lib/python3.6/site-packages/yrd/xcjdns.py", line 154, in __init__
    kwargs['ip'] = addr2ip(kwargs['addr'])
  File "/usr/lib/python3.6/site-packages/yrd/xcjdns.py", line 214, in addr2ip
    return pk2ipv6(addr[24:])
  File "/usr/lib/python3.6/site-packages/yrd/cjdns/cjdns.py", line 328, in PublicToIp6
    keyBytes = Base32_decode(pubKey[0:-2])
  File "/usr/lib/python3.6/site-packages/yrd/cjdns/cjdns.py", line 320, in Base32_decode
    raise ValueError("bits is %s and nextByte is %s" % (bits, nextByte))
ValueError: bits is 7 and nextByte is 2
```

**Comment by kpcyrd** [comment]
@matkam Thanks for reporting this, I was able to reproduce this. I've made sure the response parser of cjdns is more robust and published v0.5.2 as a bugfix.

**Comment by matkam** [comment]
You're quick @kpcyrd. Glad you were able to reproduce it and thanks for fixing it. Looks like it was just a bug in parsing the public key.

**Comment by kpcyrd** [comment]
@matkam The problem was that the code assumed that the `addr` field in the response has a fixed size and you can parse it by using offsets. This works if cjdroute correctly discovered the version of your peer (eg `v19`, `v20`) but fails if you have never been able to connect to your peer, causing the version to be `v0`, which is too short and causes the offset to be off-by-one. I've solved this by splitting at the dots instead of assuming the public key at a fixed position. (#15)

Out of interest, on which platform are you using yrd? I'm considering a reimplementation in rust and I'm trying to avoid causing trouble for existing users. :)

**Comment by matkam** [comment]
@kpcyrd I think that makes sense. I haven't found a reliable peer yet.
So far I've run yrd on Arch Linux. I could possibly run it on my Mac laptop, or even a VPS in the future after I understand how cjdns works a bit better.
