### ISSUE TITLE
Error with sub-commands that read cjdroute.conf

### ISSUE THREAD

**Issue by matkam** [kpcyrd/yrd#16]
Here's another that happens with sub commands that read `/etc/cjdroute.conf`:

```
$ sudo yrd peer ls
Traceback (most recent call last):
  File "/bin/yrd", line 11, in <module>
    load_entry_point('yrd==0.5.2', 'console_scripts', 'yrd')()
  File "/usr/lib/python3.6/site-packages/yrd/__init__.py", line 14, in main
    dispatch(parser)
  File "/usr/lib/python3.6/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/usr/lib/python3.6/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/usr/lib/python3.6/site-packages/argh/dispatching.py", line 265, in _call
    for line in result:
  File "/usr/lib/python3.6/site-packages/yrd/peer.py", line 112, in ls
    for user in c.listPasswords()['users']:
AttributeError: 'Session' object has no attribute 'listPasswords'
```

**Comment by kpcyrd** [comment]
Sorry for the late reply and thanks for reporting this, I've pushed a commit to resolve this issue, could you try this again with the branch linked above?
