### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by hengestone** [kpcyrd/yrd#18]
Following the instructions for Ubuntu/Debian in the readme, I get:
```
Traceback (most recent call last):
  File "/usr/local/bin/yrd", line 9, in <module>
    load_entry_point('yrd==0.5.2', 'console_scripts', 'yrd')()
  File "/usr/local/lib/python3.5/dist-packages/yrd-0.5.2-py3.5.egg/yrd/__init__.py", line 14, in main
  File "/usr/local/lib/python3.5/dist-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/usr/local/lib/python3.5/dist-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/usr/local/lib/python3.5/dist-packages/argh/dispatching.py", line 265, in _call
    for line in result:
  File "/usr/local/lib/python3.5/dist-packages/yrd-0.5.2-py3.5.egg/yrd/start.py", line 15, in start
TypeError: __init__() got an unexpected keyword argument 'encoding'
```

Might be related to `argh` encoding handling?

**Comment by kpcyrd** [comment]
Thanks for reporting this, I've pushed a commit to resolve this issue, could you try this again with the branch linked above?

**Comment by hengestone** [comment]
Fixes the issue, thanks!
