### ISSUE TITLE
AttributeError: 'Session' object has no attribute 'sessionStats'

### ISSUE THREAD

**Issue by hengestone** [kpcyrd/yrd#20]
Doing `yrd sessions` in the current `bugs` branch results in:
```
Traceback (most recent call last):
  File "/usr/local/bin/yrd", line 9, in <module>
    load_entry_point('yrd==0.5.2', 'console_scripts', 'yrd')()
  File "/usr/local/lib/python3.5/dist-packages/yrd-0.5.2-py3.5.egg/yrd/__init__.py", line 14, in main
  File "/usr/local/lib/python3.5/dist-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/usr/local/lib/python3.5/dist-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/usr/local/lib/python3.5/dist-packages/argh/dispatching.py", line 265, in _call
    for line in result:
  File "/usr/local/lib/python3.5/dist-packages/yrd-0.5.2-py3.5.egg/yrd/core.py", line 226, in sessions
AttributeError: 'Session' object has no attribute 'sessionStats'
```

**Comment by kpcyrd** [comment]
thanks, I've pushed a fix to the bugs branch together with fixes for 2 other subcommands.

**Comment by hengestone** [comment]
Verified fixed :+1:
